<?php
require __DIR__.'/config.php';
$user = require_login();
$pdo = db();
$month = preg_match('/^\d{4}-\d{2}$/', $_GET['month'] ?? '') ? $_GET['month'] : date('Y-m');
$employeeId = $user['role'] === 'employee' ? $user['emp_id'] : trim($_GET['emp'] ?? '');
$filename = 'attendance-'.($employeeId ?: 'all').'-'.$month.'.pdf';
$sql = 'SELECT a.attendance_date,e.emp_code,e.name,e.department,a.status,a.punch_in,a.punch_out,a.working_minutes,a.late_minutes,a.early_out_minutes,a.overtime_minutes,a.approval_status FROM attendance_records a JOIN employees e ON e.id=a.emp_id WHERE DATE_FORMAT(a.attendance_date, "%Y-%m")=?';
$params = [$month];
if ($employeeId !== '') {
    $sql .= ' AND a.emp_id=?';
    $params[] = $employeeId;
}
$sql .= ' ORDER BY a.attendance_date DESC,e.emp_code';
$statement = $pdo->prepare($sql);
$statement->execute($params);

header('Content-Type: application/pdf');
header('Content-Disposition: attachment; filename="'.$filename.'"');
$lines = [
    'HRMS ATTENDANCE REPORT',
    'Month: '.$month.'    Employee: '.($employeeId ?: 'All employees'),
    str_repeat('-', 118),
    'Date       ID       Employee              Status  In       Out      Work  Late  Early  OT  Approval',
    str_repeat('-', 118),
];
while ($row = $statement->fetch(PDO::FETCH_ASSOC)) {
    $lines[] = sprintf('%-10s %-8s %-21s %-7s %-8s %-8s %5d %5d %6d %3d %-8s',
        $row['attendance_date'], $row['emp_code'], substr($row['name'], 0, 21), $row['status'],
        $row['punch_in'] ?: '-', $row['punch_out'] ?: '-', (int)$row['working_minutes'],
        (int)$row['late_minutes'], (int)$row['early_out_minutes'], (int)$row['overtime_minutes'], $row['approval_status']);
}
$lines[] = str_repeat('-', 118);
$lines[] = 'Generated by HRMS on '.date('Y-m-d H:i');

function pdf_escape(string $value): string
{
    return str_replace(['\\', '(', ')'], ['\\\\', '\\(', '\\)'], $value);
}

$pageChunks = array_chunk($lines, 46);
$objects = [];
$objects[] = '<< /Type /Catalog /Pages 2 0 R >>';
$pageNumbers = [];
$nextObject = 4;
foreach ($pageChunks as $chunk) {
    $pageNumbers[] = $nextObject;
    $nextObject += 2;
}
$kids = implode(' ', array_map(fn($number) => $number.' 0 R', $pageNumbers));
$objects[] = '<< /Type /Pages /Kids ['.$kids.'] /Count '.count($pageNumbers).' >>';
$objects[] = '<< /Type /Font /Subtype /Type1 /BaseFont /Courier >>';
foreach ($pageChunks as $chunk) {
    $pageObject = count($objects) + 1;
    $contentObject = $pageObject + 1;
    $content = "BT /F1 8 Tf 36 760 Td 10 TL\n";
    foreach ($chunk as $line) {
        $content .= '('.pdf_escape(substr($line, 0, 118)).') Tj T*' . "\n";
    }
    $content .= 'ET';
    $objects[] = '<< /Type /Page /Parent 2 0 R /MediaBox [0 0 842 842] /Resources << /Font << /F1 3 0 R >> >> /Contents '.$contentObject.' 0 R >>';
    $objects[] = '<< /Length '.strlen($content).' >> stream' . "\n" . $content . "\nendstream";
}
$pdf = "%PDF-1.4\n";
$offsets = [0];
foreach ($objects as $number => $object) {
    $objectNumber = $number + 1;
    $offsets[$objectNumber] = strlen($pdf);
    $pdf .= $objectNumber." 0 obj\n".$object."\nendobj\n";
}
$xref = strlen($pdf);
$pdf .= "xref\n0 ".(count($objects) + 1)."\n0000000000 65535 f \n";
for ($number = 1; $number <= count($objects); $number++) {
    $pdf .= sprintf("%010d 00000 n \n", $offsets[$number]);
}
$pdf .= "trailer\n<< /Size ".(count($objects) + 1)." /Root 1 0 R >>\nstartxref\n".$xref."\n%%EOF";
echo $pdf;
